### ISSUE TITLE
Create an Icon for IOT-Hubber

### ISSUE THREAD

**Issue by VeronikaHillebrand** [deviceinsight/iot-hubber#1]
Design an icon for IOT Hubber.

IOT Hubber is a tool for sending data to the Azure IOT hub via mqtt.

It would be nice to have an icon symbolising this.

Desired Exports:
* 64x64 as a favicon to client/public/favicon.ico
* ?x200 as a png to client/public/logo.png for future use as a logo etc

**Comment by pniedzwiedzinski** [comment]
Maybe something like this:
![image](https://user-images.githubusercontent.com/19212948/65957216-916d0800-e44c-11e9-98c8-5b0afca90356.png)

**Comment by pniedzwiedzinski** [comment]
But there’s little „IOT” in it.

**Comment by VeronikaHillebrand** [comment]
I like it :) If you export it to a favicon and logo, I will accept the PR!

**Comment by pniedzwiedzinski** [comment]
How about transparency?
![image](https://user-images.githubusercontent.com/19212948/65981052-9778de00-e478-11e9-891e-b2b811fdf8d7.png)

**Comment by VeronikaHillebrand** [comment]
The one with the white lines (on the right-hand side) is cool!
