### ISSUE TITLE
Design Login page responsively

### ISSUE THREAD

**Issue by VeronikaHillebrand** [deviceinsight/iot-hubber#2]
At the moment, the login page is not very visually appealing :grin:

The top banner cuts off when the page height is smaller than ca 480px.

We are open to using a component library, if someone would like to pull one in.

Styles relating to a particular component should be on the same level as the component.
Styles applicable to the whole app should be in App.scss.

**Comment by nimitbhargava** [comment]
@VeronikaHillebrand I'd like to take a stab at this issue. Is it available?

**Comment by VeronikaHillebrand** [comment]
Hi @nimitbhargava, I would be happy for you to take a stab at it, if you are still up for it! As I mentioned in the other issue, just use dummy data for IOTHUB_URL and IOTHUB_BROKER, if you have no Azure IOT Hub.

**Comment by nimitbhargava** [comment]
Just want to update - I will continue to work on this.
I am yet to setup the project in local. I will try to pick it up soon.

**Comment by VeronikaHillebrand** [comment]
Sure, there is no rush. We now also have a nice logo to integrate, if you like.

**Comment by douglasgc** [comment]
PR: 
https://github.com/deviceinsight/iot-hubber/pull/14

**Comment by VeronikaHillebrand** [comment]
Hi @nimitbhargava, are you still working on this issue? If not, I would like to accept the Pull Request from @douglasgc

**Comment by nimitbhargava** [comment]
@VeronikaHillebrand Unfortunately I haven't start this. Please go ahead.

@douglasgc Thanks!

**Comment by VeronikaHillebrand** [comment]
And from me too! Thanks everyone!
